name: portfolio
description: Portfolio Project
publish_to: 'none'

version: 3.0.0+1

environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
    
  google_fonts: ^6.3.3
  font_awesome_flutter: ^10.12.0
  
    
  
  #-------------------------------------------------------------

  # Widgets
  flutter_advanced_drawer: ^1.5.0
  flutter_svg: ^2.2.3
  auto_size_text: ^3.0.0
  animated_text_kit: ^4.3.0
  flutter_html: ^3.0.0
  scrollable_positioned_list: ^0.3.8
  day_night_themed_switcher: ^2.0.2
  cached_network_image: ^3.4.1
  lava_lamp_effect: ^1.0.3

  # Core
  url_launcher: ^6.3.2
  page_transition: ^2.2.1
  resize: ^1.0.0
  intl: ^0.20.2
  gap: ^3.0.1
  http: ^1.6.0
  oktoast: ^3.4.0
  flutter_riverpod: ^3.0.3
  shared_preferences: ^2.5.4
#  cached_network_image_platform_interface: ^4.1.1
  flutter_markdown_plus: ^1.0.6
  cached_network_image_platform_interface: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: space_grotesk
      fonts:
        - asset: assets/fonts/sg300.ttf
          weight: 300
        - asset: assets/fonts/sg400.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/sg500.ttf
          weight: 500
        - asset: assets/fonts/sg600.ttf
          weight: 600
        - asset: assets/fonts/sg700.ttf
          weight: 700

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/logo/