name: portfolio
description: Portfolio Project
publish_to: 'none'

version: 4.0.0+53

environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  
  google_fonts: ^6.3.3
  font_awesome_flutter: ^10.12.0
  url_launcher: ^6.3.2
  flutter_svg: ^2.2.3
  auto_size_text: ^3.0.0
  day_night_themed_switcher: ^2.0.2
  cached_network_image: ^3.4.1
  cached_network_image_platform_interface: ^4.1.1
  flutter_markdown_plus: ^1.0.6
  shared_preferences: ^2.5.4
  intl: ^0.20.2
  gap: ^3.0.1
  http: ^1.6.0
  oktoast: ^3.4.0
  lava_lamp_effect: ^1.0.3
  animated_text_kit: ^4.3.0
  
dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/logo/